### ISSUE TITLE
little error here, should be taggram.T instead of taggram.numpy().T

### ISSUE THREAD

**Issue by nieguangyang** [Quint-e/musicnn_keras#2]
https://github.com/Quint-e/musicnn_keras/blob/6cd50435bca4e98041e10da73a1c0809ec3227ee/musicnn_example.py#L15

**Comment by Quint-e** [comment]
Could explain in a bit more detail why this is an error, or what kind of error you are getting with this?

**Comment by nieguangyang** [comment]
”
Traceback (most recent call last):
  File "/Users/nieguangyang/PycharmProjects/musicnn_keras/musicnn_example.py", line 15, in <module>
    ax.imshow(taggram.numpy().T, interpolation=None, aspect="auto")
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'
“

**Comment by Quint-e** [comment]
I cannot reproduce your error when running [`musicnn_keras/musicnn_example.py`](https://github.com/Quint-e/musicnn_keras/blob/6cd50435bca4e98041e10da73a1c0809ec3227ee/musicnn_example.py#L15).

Your traceback suggests that `taggram` is a Numpy array, but it should be a TF Tensor. This is the data type that was intended in the code and it is also what I get when running the code. I would assume that you may have converted `taggram` into a Numpy array before passing it to `ax.imshow`.

**Comment by nieguangyang** [comment]
It is strange that when I ran exactly the same code, the taggram is a numpy array...
However, it is not a big issue. Thank you for your response.

**Comment by Quint-e** [comment]
No problem.
I am happy to look into it further if you are able share a minimal code snippet that reproduces the error.

**Comment by nieguangyang** [comment]
I re-run the downloaded original code again, still same issue. `taggram` from extractor is a numpy array.
Could difference of development environment be the reason of this issue? 
By the way, mine is pycharm + py3.8 + tf2.3.0 on mac. The MTT and MSD musicnn are small, so I haven't run it on linux GPU server yet.

**Comment by Quint-e** [comment]
I am not sure how the environment could have an impact on the data type. In order to test this maybe try setting up a fresh environment (venv or even better with Docker) and see if the issue persists.

This may be a long shot, but in Jordi Pons' [original Musicnn repo](https://github.com/jordipons/musicnn), the `extractor` function in `extractor.py` outputs a Numpy array. If you ever used this code, you may want to double check that the `extractor` import is not being messed up between the two repos. In other words, if your code somehow uses Jordi's `extractor` function instead of the one in this repository, it could be the explanation. 
Note that setting up a fresh environment should also eliminate this possibility.
